POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username":"QuangTruong",
    "email": "email",
    "password":"123"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "virustinhyeu111",
    "password": "123"
}

###
GET http://13.229.105.112:5000/api/generals
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGEwOTg4MDMyMzdjZDRjYzA1MjA3YzYiLCJpYXQiOjE2MjExMzc1MzZ9.Gqypep5R76M16zW5fNMIyYDA9mY_TK3sARwnPTA4aI0

###
PUT http://localhost:5000/api/user/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGEwOTg4MDMyMzdjZDRjYzA1MjA3YzYiLCJpYXQiOjE2MjExMzc1MzZ9.Gqypep5R76M16zW5fNMIyYDA9mY_TK3sARwnPTA4aI0

{
    "address": "Đường số 16, phường Long Thạnh Mỹ, Q9, HCM",
    "fullname": "Trần Nguyễn Quang Trường",
    "email": "karikbeau@gmail.com",
    "company": "Đại học CNTT UIT",
    "number": "0945801840",
}

###
POST http://localhost:5000/api/generals/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGEwOTg4MDMyMzdjZDRjYzA1MjA3YzYiLCJpYXQiOjE2MjExMzc1MzZ9.Gqypep5R76M16zW5fNMIyYDA9mY_TK3sARwnPTA4aI0

{
    "temperature":"31",
    "oil": "45%",
    "co2":"100pm"
}